@baseUrl = http://localhost:3000

### Inventories (all)
GET {{baseUrl}}/api/inventories
Accept: application/json


### Inventories (search por codigo o descripcion)
GET {{baseUrl}}/api/inventories?q=TUBO
Accept: application/json

### Inventories (pagination)
GET {{baseUrl}}/api/inventories?limit=10&offset=0
Accept: application/json

### Inventory detail by code
GET {{baseUrl}}/api/inventories/01100104
Accept: application/json

### Inventory warehouses by code
GET {{baseUrl}}/api/inventories/01100104/warehouses
Accept: application/json

### Inventory auxiliar by code
GET {{baseUrl}}/api/inventories/01300938/auxiliar
Accept: application/json

### Inventory orders by client
GET {{baseUrl}}/api/inventories/01300938/orders-by-client
Accept: application/json
